[package]
name = "gbar"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", package = "gpui", default-features = false, features = ["wayland"] }
gpui_platform = { git = "https://github.com/zed-industries/zed", default-features = false, package = "gpui_platform", features = ["wayland"] }
gpui_linux = { git = "https://github.com/zed-industries/zed", default-features = false, package = "gpui_linux", features = ["wayland"] }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
chrono = "0.4.42"
image = "0.25"
dirs = "6"
battery = "0.7.8"
niri-ipc = "26.4.0"
anyhow = "1.0.102"
smol = "2.0.2"

[profile.dev]
opt-level = 1
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
